#!/bin/sh

if [ "$#" -ge 1 ]
then
    for f in "$@"
    do
        f=$(readlink -f "$f")
        printf '==> %s <==\n' "$f"
        result=$(nc x7f.uk 44 < "$f")
        filename="${f##*/}"
        fileext="${filename##*.}"
        printf '\t%s\n\t%s\n' "$result" "${result}.${fileext}"
    done
else
    nc x7f.uk 44
fi
